export const ACTION_CHANGE_LOGGED_IN = 'ACTION_CHANGE_LOGGED_IN';
export const ACTION_CHANGE_LOADING = 'ACTION_CHANGE_LOADING';
export const ACTION_CHANGE_ALERT = 'ACTION_CHANGE_ALERT';
export const CREATE_CAR_TYPE = 'CREATE_CAR_TYPE';
