export const CHANGE_LOGGED_IN = 'CHANGE_LOGGED_IN';
export const CHANGE_LOADING = 'CHANGE_LOADING';
export const CHANGE_ALERT = 'CHANGE_ALERT';
export const ADD_USERS = 'ADD_USERS';
export const CLEAR_USERS = 'CLEAR_USERS';
export const ADD_UNVERIFIED_USERS = 'ADD_UNVERIFIED_USERS';
export const CREATE_CAR_TYPE = 'CREATE_CAR_TYPE';
